---
title: "Learning Module 2: Risk Management (NG-SOC LM2)"
description: |
  Training scenario comprising two hands-on exercises focused on proactive
  cybersecurity risk management in critical sectors (financial and energy).
  Learners use the RITA platform for dynamic risk analysis throughout the
  exercises.
  Participants take on the role of a Cybersecurity Risk Manager for (1) a
  banking institution and (2) an energy infrastructure, conducting asset
  identification and threat modelling, risk assessment (likelihood and impact),
  and designing mitigations. Exercises are aligned with frameworks such as
  MITRE ATT&CK, STRIDE, and the ENISA European Cybersecurity Skills Framework
  (ECSF), and are tailored for intermediate to advanced learners in roles such
  as Risk Manager and Security Architect. The training includes supporting
  artefacts (e.g., network diagrams, risk matrices) and guided steps.
prerequisites:
  - >
    Basic cybersecurity knowledge (threats, vulnerabilities, security controls).
  - >
    Familiarity with risk assessment methodologies (e.g. ISO 27005, NIST 800-30)
    and attack frameworks.
outcomes:
  - >
    Apply threat modelling methodologies (e.g. STRIDE, MITRE ATT&CK) to identify
    vulnerabilities and attack scenarios in banking and ICS/SCADA systems.
  - >
    Qualitatively assess risks (likelihood and impact) and prioritise them based
    on business and safety consequences.
  - >
    Recommend security controls and mitigation strategies (technical and
    procedural) aligned with defence-in-depth principles.
  - >
    Translate technical risk analysis into clear action plans for both
    technical teams and executives.
  - >
    Adapt risk management approaches to industrial (OT/ICS) environments,
    accounting for availability and physical safety considerations.
  - >
    Develop proficiency in RITA-based modelling and risk evaluation.
state: "RELEASED"
show_stepper_bar: true
levels:
  - title: "Exercise 1: Risk Assessment and Threat Modelling (Banking Sector)"
    level_type: "TRAINING_LEVEL"
    order: 1
    estimated_duration: 90
    content: |
      *(Detailed exercise content is provided in **content/exercise1.md**)*
    answer: |
      **Expected findings**
      - Inventory of critical banking assets (core banking services, digital channels, SWIFT interfaces, customer databases).
      - Mapping of dependencies between internal systems and third parties, including cloud services and payment processors.
      - Threat identification aligned with MITRE ATT&CK for financial environments (targeted phishing, credential abuse, data exfiltration).
      - Evaluation of existing controls (MFA, fraud monitoring, segregation of duties) and detection of coverage gaps.

      **Identified risks**
      - Compromise of privileged credentials enabling fraudulent transactions or manipulation of accounting records.
      - Ransomware affecting payment platforms, disrupting availability and threatening regulatory compliance.
      - Exfiltration of sensitive customer data resulting in PSD2/GDPR penalties and reputational damage.
      - Over-reliance on external suppliers without strong business continuity plans.

      **Recommended mitigations**
      - Deploy privileged access management with continuous monitoring and credential rotation.
      - Enhance phishing resilience through awareness campaigns, advanced filtering and stronger authentication journeys.
      - Implement network segmentation and tested immutable backups to limit ransomware impact.
      - Formalise SLAs and contingency plans with key suppliers and rehearse recovery procedures.
      - Integrate anomalous behaviour alerts into the SIEM and align incident response playbooks with business stakeholders.
    answer_variable_name: null
  - title: |
      Exercise 2: Risk Assessment and Threat Modelling
      (ICS Energy Infrastructure)
    level_type: "TRAINING_LEVEL"
    order: 2
    estimated_duration: 90
    content: |
      *(Detailed exercise content is provided in **content/exercise2.md**)*
    answer: |
      **Expected findings**
      - Comprehensive inventory of OT components (SCADA, PLCs, RTUs, field networks) and dependencies with IT services.
      - Updated ISA/IEC 62443-aligned zones and conduits diagram noting remote access paths.
      - Threat catalogue referencing MITRE ATT&CK for ICS (remote engineering compromise, process manipulation).
      - Assessment of current controls such as industrial firewalls, application whitelisting and OT change policies.

      **Identified risks**
      - Lateral movement from corporate IT into the industrial DMZ that degrades SCADA operations.
      - Malicious modification of PLC parameters interrupting power generation or distribution.
      - Denial-of-service on critical communications with insufficient redundancy between control centres.
      - Shared remote maintenance credentials lacking supervision and audit trails.

      **Recommended mitigations**
      - Deploy continuous OT network monitoring with anomaly detection for industrial protocols.
      - Enforce role-based access control and multi-factor authentication for remote engineering sessions.
      - Strengthen segmentation between IT/OT and critical zones using next-generation firewalls and minimal ACLs.
      - Institute validated patch and change management workflows with testing prior to production deployment.
      - Design and exercise OT incident response plans coordinated with operations teams and suppliers.
    answer_variable_name: null
estimated_duration: 180
variant_sandboxes: true
